-- ============================================================================
-- RoomMate - Complete Database Schema with RLS Policies, Functions & Triggers
-- ============================================================================
-- Run this ENTIRE file in your Supabase SQL Editor
-- This will set up everything needed for the application to work properly
-- ============================================================================

-- ============================================================================
-- STEP 1: DROP EXISTING POLICIES (Clean slate)
-- ============================================================================

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own profile" ON public.users;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.users;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.users;
DROP POLICY IF EXISTS "owners_insert_own_listings" ON public.listings;
DROP POLICY IF EXISTS "owners_manage_own" ON public.listings;
DROP POLICY IF EXISTS "owners_delete_own" ON public.listings;
DROP POLICY IF EXISTS "admin_manage_all" ON public.listings;
DROP POLICY IF EXISTS "public_select_approved" ON public.listings;
DROP POLICY IF EXISTS "messages_participants_insert" ON public.messages;
DROP POLICY IF EXISTS "messages_select_participants" ON public.messages;
DROP POLICY IF EXISTS "public_view_photos_approved" ON public.listing_photos;
DROP POLICY IF EXISTS "owners_manage_photos" ON public.listing_photos;

-- ============================================================================
-- STEP 2: CREATE TABLES (if not exists)
-- ============================================================================

-- Users table (additional profile fields)
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  role text NOT NULL CHECK (role IN ('tenant','owner','admin')),
  phone text,
  created_at timestamptz DEFAULT now()
);

-- Listings table
CREATE TABLE IF NOT EXISTS public.listings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  price_per_month numeric NOT NULL,
  currency text DEFAULT 'NPR',
  address_line text,
  area_name text,
  latitude double precision,
  longitude double precision,
  is_owner_occupied boolean DEFAULT false,
  water_availability text CHECK (water_availability IN ('continuous','timed','no')),
  parking text CHECK (parking IN ('none','bike_only','car_only','bike_and_car')),
  allowed_for text,
  listing_type text CHECK (listing_type IN ('room','flat')),
  status text DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','archived')),
  rejection_reason text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Listing photos table
CREATE TABLE IF NOT EXISTS public.listing_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id uuid REFERENCES public.listings(id) ON DELETE CASCADE,
  storage_path text NOT NULL,
  order_num int DEFAULT 0
);

-- Messages table
CREATE TABLE IF NOT EXISTS public.messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id uuid REFERENCES public.listings(id) ON DELETE CASCADE,
  sender_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  receiver_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz DEFAULT now(),
  is_read boolean DEFAULT false
);

-- Areas table (for dropdown)
CREATE TABLE IF NOT EXISTS public.areas (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL
);

-- ============================================================================
-- STEP 3: CREATE INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_listings_status_area ON public.listings (status, area_name);
CREATE INDEX IF NOT EXISTS idx_listings_price ON public.listings (price_per_month);
CREATE INDEX IF NOT EXISTS idx_listings_owner ON public.listings (owner_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON public.messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver ON public.messages (receiver_id);

-- ============================================================================
-- STEP 4: ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.areas ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 5: CREATE RLS POLICIES
-- ============================================================================

-- ============================================================================
-- USERS TABLE POLICIES
-- ============================================================================

-- Allow users to view their own profile
CREATE POLICY "Users can view their own profile" 
ON public.users
FOR SELECT
USING (auth.uid() = id);

-- Allow users to insert their own profile (CRITICAL FOR SIGNUP)
CREATE POLICY "Users can insert their own profile" 
ON public.users
FOR INSERT
WITH CHECK (auth.uid() = id);

-- Allow users to update their own profile
CREATE POLICY "Users can update their own profile" 
ON public.users
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Allow admins to view all users
CREATE POLICY "Admins can view all users" 
ON public.users
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.users u 
    WHERE u.id = auth.uid() AND u.role = 'admin'
  )
);

-- ============================================================================
-- LISTINGS TABLE POLICIES
-- ============================================================================

-- Public can view approved listings
CREATE POLICY "Public can view approved listings" 
ON public.listings
FOR SELECT
USING (status = 'approved');

-- Owners can view their own listings (any status)
CREATE POLICY "Owners can view their own listings" 
ON public.listings
FOR SELECT
USING (owner_id = auth.uid());

-- Owners can insert their own listings
CREATE POLICY "Owners can insert their own listings" 
ON public.listings
FOR INSERT
WITH CHECK (owner_id = auth.uid());

-- Owners can update their own listings (but not change status to approved)
CREATE POLICY "Owners can update their own listings" 
ON public.listings
FOR UPDATE
USING (owner_id = auth.uid())
WITH CHECK (owner_id = auth.uid() AND status != 'approved');

-- Owners can delete their own listings
CREATE POLICY "Owners can delete their own listings" 
ON public.listings
FOR DELETE
USING (owner_id = auth.uid());

-- Admins can do everything with listings
CREATE POLICY "Admins can manage all listings" 
ON public.listings
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.users u 
    WHERE u.id = auth.uid() AND u.role = 'admin'
  )
);

-- ============================================================================
-- LISTING PHOTOS TABLE POLICIES
-- ============================================================================

-- Public can view photos of approved listings
CREATE POLICY "Public can view photos of approved listings" 
ON public.listing_photos
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.listings l 
    WHERE l.id = listing_id AND l.status = 'approved'
  )
);

-- Owners can view photos of their own listings
CREATE POLICY "Owners can view their own listing photos" 
ON public.listing_photos
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.listings l 
    WHERE l.id = listing_id AND l.owner_id = auth.uid()
  )
);

-- Owners can insert photos for their own listings
CREATE POLICY "Owners can insert photos for their listings" 
ON public.listing_photos
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.listings l 
    WHERE l.id = listing_id AND l.owner_id = auth.uid()
  )
);

-- Owners can delete photos from their own listings
CREATE POLICY "Owners can delete their listing photos" 
ON public.listing_photos
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.listings l 
    WHERE l.id = listing_id AND l.owner_id = auth.uid()
  )
);

-- Admins can manage all photos
CREATE POLICY "Admins can manage all photos" 
ON public.listing_photos
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.users u 
    WHERE u.id = auth.uid() AND u.role = 'admin'
  )
);

-- ============================================================================
-- MESSAGES TABLE POLICIES
-- ============================================================================

-- Users can view messages where they are sender or receiver
CREATE POLICY "Users can view their own messages" 
ON public.messages
FOR SELECT
USING (sender_id = auth.uid() OR receiver_id = auth.uid());

-- Users can send messages (as sender)
CREATE POLICY "Users can send messages" 
ON public.messages
FOR INSERT
WITH CHECK (sender_id = auth.uid() AND receiver_id IS NOT NULL);

-- Users can update their own messages (for read status)
CREATE POLICY "Users can update their received messages" 
ON public.messages
FOR UPDATE
USING (receiver_id = auth.uid())
WITH CHECK (receiver_id = auth.uid());

-- ============================================================================
-- AREAS TABLE POLICIES
-- ============================================================================

-- Everyone can view areas
CREATE POLICY "Everyone can view areas" 
ON public.areas
FOR SELECT
USING (true);

-- ============================================================================
-- STEP 6: CREATE FUNCTIONS
-- ============================================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- STEP 7: CREATE TRIGGERS
-- ============================================================================

-- Trigger to update updated_at on listings
DROP TRIGGER IF EXISTS set_updated_at ON public.listings;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.listings
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================================
-- STEP 8: SEED INITIAL DATA
-- ============================================================================

-- Insert area names (for dropdown)
INSERT INTO public.areas (name) VALUES
  ('Baneshwor'),
  ('Koteshwor'),
  ('Maitidevi'),
  ('Putalisadak'),
  ('Lalitpur'),
  ('Bhaktapur'),
  ('Thamel'),
  ('Lazimpat'),
  ('Boudha'),
  ('Kalanki'),
  ('Balaju'),
  ('Chabahil'),
  ('Jorpati'),
  ('Maharajgunj'),
  ('New Baneshwor'),
  ('Patan'),
  ('Pulchowk'),
  ('Sanepa'),
  ('Satdobato'),
  ('Swayambhu')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- STEP 9: GRANT PERMISSIONS
-- ============================================================================

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO anon, authenticated;

-- Grant permissions on tables
GRANT ALL ON public.users TO authenticated;
GRANT ALL ON public.listings TO authenticated;
GRANT ALL ON public.listing_photos TO authenticated;
GRANT ALL ON public.messages TO authenticated;
GRANT SELECT ON public.areas TO anon, authenticated;

-- ============================================================================
-- VERIFICATION QUERIES (Optional - Run these to verify setup)
-- ============================================================================

-- Check if tables exist
-- SELECT tablename FROM pg_tables WHERE schemaname = 'public';

-- Check if policies exist
-- SELECT tablename, policyname FROM pg_policies WHERE schemaname = 'public';

-- Check areas data
-- SELECT * FROM public.areas;

-- ============================================================================
-- SETUP COMPLETE!
-- ============================================================================
-- You can now use the application. Try signing up as Tenant or Owner.
-- ============================================================================
