-- Seed Data for RoomMate

-- Insert Area Names (for the MVP dropdown)
-- Note: This is a simplified list. In a real app, you might have a dedicated table for areas.
-- Since the requirements say "area_name must be one of seeded options", we can just enforce this in the frontend or check constraint.
-- However, if we want to store them in the DB for the dropdown:

create table if not exists public.areas (
  id int generated by default as identity primary key,
  name text unique not null
);

insert into public.areas (name) values
('Baneshwor'),
('Koteshwor'),
('Maitidevi'),
('Putalisadak'),
('Lalitpur'),
('Bhaktapur'),
('Thamel'),
('Lazimpat'),
('Boudha'),
('Kalanki')
on conflict (name) do nothing;

-- Example Admin User Seed (You need to create the user in Auth first, then run this)
-- update public.users set role = 'admin' where id = 'YOUR_USER_ID';
